version: 2.1

parameters:
  go_version:
    description: The version of go used for this build pipeline
    type: string
    default: "1.24"

orbs:
  lambda: liveauctioneers/lambda@1.2

workflows:
  version: 2
  build_and_publish:
    jobs:
      - lambda/server_build_and_publish:
          context: la_build_vars
          go_version: <<pipeline.parameters.go_version>>
